const THEME_OPTIONS = ["LIGHT", "DARK"];
const THEME = {
  LIGHT: "LIGHT",
  DARK: "DARK",
};

const STATUS_OPTIONS = ["ACTIVE", "INACTIVE", "DELETED"];
const STATUS = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  DELETED: "DELETED",
};



export { STATUS_OPTIONS, THEME_OPTIONS , STATUS, THEME};
