export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  USER: 'USER',
};

export const POST_STATUS = {
  DRAFT: 'DRAFT',
  GENERATING: 'GENERATING',
  GENERATED: 'GENERATED',
  POSTING: 'POSTING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
};

export const POSTING_RESULTS = {
  PENDING: 'PENDING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
};

export const VISIBILITY = {
  PLATFORM: 'PLATFORM',
  PRIVATE: 'PRIVATE',
};

export const SITE_TYPES = {
  WORDPRESS: 'WORDPRESS',
  CUSTOM: 'CUSTOM',
  WOO_COMMERCE: 'WOO_COMMERCE',
};

export const ACTIONS = {
  USER_CREATED: 'USER_CREATED',
  USER_DELETED: 'USER_DELETED',
  SHEET_UPLOADED: 'SHEET_UPLOADED',
  POST_CREATED: 'POST_CREATED',
  POST_POSTED: 'POST_POSTED',
  LOGIN: 'LOGIN',
};
